# Site
name: "Crystal's Travel Log"
title: "Travel Log"
description: "Welcome :)"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
domain: auoiman.github.io
url: https://auoiman.github.io
baseurl: 
google_analytics: 'UA-477120649-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: ayowhasup@gmail.com

# Authors
authors:
  Crystal:
    name: Crystal
    display_name: CA
    avatar: 'assets/images/CA.png'
    email: ayowhasup@gmail.com
    web: https://auoiman.github.io
    twitter: https://twitter.com/
    description: "Owner of this website."
#  john:
#    name: John
#    display_name: John    
#    avatar: 'assets/images/avatar.png'
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net
#    twitter: https://twitter.com/wowthemesnet
#    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8963153216579810"
adsense-data-ad-slot: "9958557987"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
