name: Update Video Data

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight UTC
  workflow_dispatch:  # This allows you to run the action manually from the GitHub interface

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client  # Add any other dependencies your script needs

    - name: Run update script
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python exportvideos.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add video_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update video data" && git push)
